// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Ruizhe Ma",
            "email": "ruizhe_ma@tju.edu.cn"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/competition": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Competition"
                ],
                "summary": "查询所有比赛信息",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页数",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数据条数",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Competition"
                ],
                "summary": "管理员创建新比赛",
                "parameters": [
                    {
                        "type": "string",
                        "description": "比赛题目",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "比赛简介（文档链接）",
                        "name": "abstract",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "enum": [
                            "升序",
                            "降序"
                        ],
                        "type": "string",
                        "default": "降序",
                        "description": "成绩排序方式",
                        "name": "sortOrder",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "default": "20",
                        "description": "时间要求",
                        "name": "timeLimit",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "赛题docker镜像名",
                        "name": "dockerImage",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "赛题添加成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "赛题添加失败",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/competition/{competitionID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Competition"
                ],
                "summary": "查询单个比赛详细信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "赛题ID",
                        "name": "competitionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/competition.Competition"
                        }
                    },
                    "500": {
                        "description": "该赛题不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Competition"
                ],
                "summary": "管理员修改比赛赛题",
                "parameters": [
                    {
                        "type": "string",
                        "description": "赛题ID",
                        "name": "competitionID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "比赛题目",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "比赛简介（文档链接）",
                        "name": "abstract",
                        "in": "formData"
                    },
                    {
                        "enum": [
                            "升序",
                            "降序"
                        ],
                        "type": "string",
                        "description": "成绩排序方式",
                        "name": "sortOrder",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "时间要求",
                        "name": "timeLimit",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "赛题docker镜像名",
                        "name": "dockerImage",
                        "in": "formData"
                    },
                    {
                        "enum": [
                            "准备中",
                            "进行中",
                            "已结束"
                        ],
                        "type": "string",
                        "description": "赛题状态",
                        "name": "status",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "赛题更新成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "赛题更新失败",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Competition"
                ],
                "summary": "管理员删除赛题",
                "parameters": [
                    {
                        "type": "string",
                        "description": "赛题ID",
                        "name": "competitionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "赛题删除成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "赛题删除失败",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/competition/{competitionID}/record": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "summary": "查询某个赛题的提交排名",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页数",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数据条数",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "赛题ID",
                        "name": "competitionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "summary": "进行一次提交",
                "parameters": [
                    {
                        "type": "string",
                        "description": "赛题ID",
                        "name": "competitionID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "提交文件",
                        "name": "submission",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "提交成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "提交失败",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/competition/{competitionID}/record/{recordID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "summary": "查询单个提交",
                "parameters": [
                    {
                        "type": "string",
                        "description": "赛题ID",
                        "name": "competitionID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "提交记录ID",
                        "name": "recordID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/record.Record"
                        }
                    },
                    "500": {
                        "description": "该次提交不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "summary": "赛题docker更新提交跑分结果",
                "parameters": [
                    {
                        "type": "string",
                        "description": "赛题ID",
                        "name": "competitionID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "提交记录ID",
                        "name": "recordID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "得分",
                        "name": "score",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "错误信息",
                        "name": "error",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "运行时间",
                        "name": "runTime",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "状态",
                        "name": "status",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "更新失败",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "summary": "管理员删除提交记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "赛题ID",
                        "name": "competitionID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "提交记录ID",
                        "name": "recordID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "该次提交删除成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "该次提交删除失败",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/files/{filename}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Files"
                ],
                "summary": "文件下载",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文件名",
                        "name": "filename",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "500": {
                        "description": "下载失败",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/getInfo": {
            "options": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "获取登录信息",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "用户名密码错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/record": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "summary": "管理员查询所有提交记录，用户查询个人提交记录",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页数",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数据条数",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "注册",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "邮箱",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "学校",
                        "name": "school",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "注册失败",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "管理员查询所有用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页数",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数据条数",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "管理员新建用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "enum": [
                            "admin",
                            "user"
                        ],
                        "type": "string",
                        "default": "user",
                        "description": "用户角色",
                        "name": "role",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "邮箱",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "学校",
                        "name": "school",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户添加成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "用户添加失败",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/user/{userID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "查询当前登录用户的详细信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID(任意值)",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/user.User"
                        }
                    },
                    "500": {
                        "description": "当前用户权限不足",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "修改个人信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID(任意值)",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData"
                    },
                    {
                        "enum": [
                            "admin",
                            "user"
                        ],
                        "type": "string",
                        "description": "用户角色",
                        "name": "role",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "邮箱",
                        "name": "email",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "学校",
                        "name": "school",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户更新成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "用户更新失败",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "管理员删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID(任意值)",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户删除成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "用户删除失败",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "competition.Competition": {
            "type": "object",
            "properties": {
                "abstract": {
                    "type": "string"
                },
                "author": {
                    "type": "string"
                },
                "createTime": {
                    "type": "string"
                },
                "dockerImage": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isDelete": {
                    "type": "boolean"
                },
                "latestTime": {
                    "type": "string"
                },
                "sortOrder": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "timeLimit": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "record.Record": {
            "type": "object",
            "properties": {
                "competitionID": {
                    "type": "string"
                },
                "createTime": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "finishTime": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isDelete": {
                    "type": "boolean"
                },
                "latestTime": {
                    "type": "string"
                },
                "runTime": {
                    "type": "integer"
                },
                "score": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "submission": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "user.User": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isDelete": {
                    "type": "boolean"
                },
                "latestTime": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "school": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Ladder Competition Platform",
	Description:      "↑ ↑ ↓ ↓ ← → ← → B A",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
